# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textLeft = QtWidgets.QLabel(self.centralwidget)
        self.textLeft.setGeometry(QtCore.QRect(70, 60, 67, 17))
        self.textLeft.setObjectName("textLeft")
        self.pushButtonLeft = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLeft.setGeometry(QtCore.QRect(60, 130, 89, 30))
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.textMid = QtWidgets.QLabel(self.centralwidget)
        self.textMid.setGeometry(QtCore.QRect(210, 60, 67, 17))
        self.textMid.setObjectName("textMid")
        self.pushButtonMid = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMid.setGeometry(QtCore.QRect(200, 130, 89, 30))
        self.pushButtonMid.setObjectName("pushButtonMid")
        self.textRight = QtWidgets.QLabel(self.centralwidget)
        self.textRight.setGeometry(QtCore.QRect(350, 60, 67, 17))
        self.textRight.setObjectName("textRight")
        self.pushButtonRight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRight.setGeometry(QtCore.QRect(340, 130, 89, 30))
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.horizontalSliderDown = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSliderDown.setGeometry(QtCore.QRect(30, 190, 160, 16))
        self.horizontalSliderDown.setMaximum(100)
        self.horizontalSliderDown.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDown.setObjectName("horizontalSliderDown")
        self.verticalSliderRight = QtWidgets.QSlider(self.centralwidget)
        self.verticalSliderRight.setGeometry(QtCore.QRect(480, 30, 16, 160))
        self.verticalSliderRight.setMaximum(100)
        self.verticalSliderRight.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderRight.setObjectName("verticalSliderRight")
        self.horizontalSliderDownTextBar = QtWidgets.QLabel(self.centralwidget)
        self.horizontalSliderDownTextBar.setGeometry(QtCore.QRect(90, 210, 67, 17))
        self.horizontalSliderDownTextBar.setObjectName("horizontalSliderDownTextBar")
        self.verticalSliderRightTextBar = QtWidgets.QLabel(self.centralwidget)
        self.verticalSliderRightTextBar.setGeometry(QtCore.QRect(500, 90, 67, 17))
        self.verticalSliderRightTextBar.setObjectName("verticalSliderRightTextBar")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(50, 280, 331, 251))
        self.camera.setText("")
        self.camera.setObjectName("camera")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textLeft.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonLeft.setText(_translate("MainWindow", "PushButton"))
        self.textMid.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonMid.setText(_translate("MainWindow", "PushButton"))
        self.textRight.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonRight.setText(_translate("MainWindow", "PushButton"))
        self.horizontalSliderDownTextBar.setText(_translate("MainWindow", "value"))
        self.verticalSliderRightTextBar.setText(_translate("MainWindow", "value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
